export const dataOptions = {
  countries: ["India", "USA", "UK"],
  subscriptions: ["free", "paid", "premium"],
  os: ["Windows", "macOS", "Linux"],
  osVersions: ["Windows 10", "macOS Catalina", "Ubuntu 20.04"],
  modelNames: ["Model A", "Model B", "Model C"],
  plans: ["Basic", "Standard", "Premium"],
  states: ["A", "B", "C"],
};

export const data = {
  countries: {
    India: 1000,
    USA: 500,
    UK: 300,
  },
  subscriptions: {
    free: 700,
    paid: 600,
    premium: 500,
  },
  os: {
    Windows: 1000,
    macOS: 500,
    Linux: 300,
  },
  osVersions: {
    "Windows 10": 800,
    "macOS Catalina": 400,
    "Ubuntu 20.04": 200,
  },
  modelNames: {
    "Model A": 600,
    "Model B": 500,
    "Model C": 300,
  },
  plans: {
    Basic: 400,
    Standard: 600,
    Premium: 800,
  },
  states: {
    A: 400,
    B: 600,
    C: 800,
  },
};

export const entries = [
  { 
    srNumber: 1, 
    country: "India", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "India", Subscription: "free" }, // Dummy body values
    headers: { CountryHeader: "India", SubscriptionHeader: "free" }, // Dummy header values
    projectId: "proj1",
    companyId: "comp1",
  },
  { 
    srNumber: 2, 
    country: "India", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "India", Subscription: "paid" },
    headers: { CountryHeader: "India", SubscriptionHeader: "paid" },
    projectId: "proj2",
    companyId: "comp1",
  },
  { 
    srNumber: 3, 
    country: "India", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "India", Subscription: "premium" },
    headers: { CountryHeader: "India", SubscriptionHeader: "premium" },
    projectId: "proj3",
    companyId: "comp1",
  },
  { 
    srNumber: 4, 
    country: "India", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "India", Subscription: "free" },
    headers: { CountryHeader: "India", SubscriptionHeader: "free" },
    projectId: "proj4",
    companyId: "comp1",
  },
  { 
    srNumber: 5, 
    country: "India", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "India", Subscription: "paid" },
    headers: { CountryHeader: "India", SubscriptionHeader: "paid" },
    projectId: "proj5",
    companyId: "comp1",
  },
  { 
    srNumber: 6, 
    country: "India", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "India", Subscription: "premium" },
    headers: { CountryHeader: "India", SubscriptionHeader: "premium" },
    projectId: "proj6",
    companyId: "comp1",
  },
  { 
    srNumber: 7, 
    country: "India", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "India", Subscription: "free" },
    headers: { CountryHeader: "India", SubscriptionHeader: "free" },
    projectId: "proj7",
    companyId: "comp1",
  },
  { 
    srNumber: 8, 
    country: "India", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "India", Subscription: "paid" },
    headers: { CountryHeader: "India", SubscriptionHeader: "paid" },
    projectId: "proj8",
    companyId: "comp1",
  },
  { 
    srNumber: 9, 
    country: "India", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "India", Subscription: "premium" },
    headers: { CountryHeader: "India", SubscriptionHeader: "premium" },
    projectId: "proj9",
    companyId: "comp1",
  },
  { 
    srNumber: 10, 
    country: "India", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "India", Subscription: "free" },
    headers: { CountryHeader: "India", SubscriptionHeader: "free" },
    projectId: "proj10",
    companyId: "comp1",
  },
  { 
    srNumber: 11, 
    country: "USA", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "free" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "free" },
    projectId: "proj11",
    companyId: "comp2",
  },
  { 
    srNumber: 12, 
    country: "USA", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "paid" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "paid" },
    projectId: "proj12",
    companyId: "comp2",
  },
  { 
    srNumber: 13, 
    country: "USA", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "premium" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "premium" },
    projectId: "proj13",
    companyId: "comp2",
  },
  { 
    srNumber: 14, 
    country: "USA", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "free" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "free" },
    projectId: "proj14",
    companyId: "comp2",
  },
  { 
    srNumber: 15, 
    country: "USA", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "paid" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "paid" },
    projectId: "proj15",
    companyId: "comp2",
  },
  { 
    srNumber: 16, 
    country: "USA", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "premium" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "premium" },
    projectId: "proj16",
    companyId: "comp2",
  },
  { 
    srNumber: 17, 
    country: "USA", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "free" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "free" },
    projectId: "proj17",
    companyId: "comp2",
  },
  { 
    srNumber: 18, 
    country: "USA", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "paid" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "paid" },
    projectId: "proj18",
    companyId: "comp2",
  },
  { 
    srNumber: 19, 
    country: "USA", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "premium" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "premium" },
    projectId: "proj19",
    companyId: "comp2",
  },
  { 
    srNumber: 20, 
    country: "USA", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "USA", Subscription: "free" },
    headers: { CountryHeader: "USA", SubscriptionHeader: "free" },
    projectId: "proj20",
    companyId: "comp2",
  },
  { 
    srNumber: 21, 
    country: "UK", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "free" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "free" },
    projectId: "proj21",
    companyId: "comp3",
  },
  { 
    srNumber: 22, 
    country: "UK", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "paid" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "paid" },
    projectId: "proj22",
    companyId: "comp3",
  },
  { 
    srNumber: 23, 
    country: "UK", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "premium" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "premium" },
    projectId: "proj23",
    companyId: "comp3",
  },
  { 
    srNumber: 24, 
    country: "UK", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "free" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "free" },
    projectId: "proj24",
    companyId: "comp3",
  },
  { 
    srNumber: 25, 
    country: "UK", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "paid" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "paid" },
    projectId: "proj25",
    companyId: "comp3",
  },
  { 
    srNumber: 26, 
    country: "UK", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "premium" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "premium" },
    projectId: "proj26",
    companyId: "comp3",
  },
  { 
    srNumber: 27, 
    country: "UK", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "free" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "free" },
    projectId: "proj27",
    companyId: "comp3",
  },
  { 
    srNumber: 28, 
    country: "UK", 
    subscription: "paid", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "paid" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "paid" },
    projectId: "proj28",
    companyId: "comp3",
  },
  { 
    srNumber: 29, 
    country: "UK", 
    subscription: "premium", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "premium" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "premium" },
    projectId: "proj29",
    companyId: "comp3",
  },
  { 
    srNumber: 30, 
    country: "UK", 
    subscription: "free", 
    actionItems: "view",
    body: { Country: "UK", Subscription: "free" },
    headers: { CountryHeader: "UK", SubscriptionHeader: "free" },
    projectId: "proj30",
    companyId: "comp3",
  },
];
